### ISSUE TITLE
Python 3 installation error

### ISSUE THREAD

**Issue by bernhardwinkel** [RDFLib/rdflib-leveldb#4]
Doing "pip install git+https://github.com/RDFLib/rdflib-leveldb.git" yields the traceback:

Collecting git+https://github.com/RDFLib/rdflib-leveldb.git
  Cloning https://github.com/RDFLib/rdflib-leveldb.git to /tmp/pip-6ay4h1t8-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-6ay4h1t8-build/setup.py", line 104, in <module>
        Extension("rdflib_leveldb.picklr", ["rdflib_leveldb/picklr.pyx"])
    NameError: name 'Extension' is not defined

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-6ay4h1t8-build/

Adding "from setuptools.extension import Extension" below line 9 in setup.py apparently did the trick.

**Comment by gjhiggins** [comment]
Fixed, picklr removed in revamp.
